#!/bin/sh

log_info () { echo "--- INF ---: $1"; }

DOTFILE_DIR="$(cd "$(dirname "$0")" && pwd)"

log_info "Dotfile directory: $DOTFILE_DIR"

# base
stow -d $DOTFILE_DIR -t $HOME shell git tmux crontab misc
# language
stow -d $DOTFILE_DIR -t $HOME ruby lisp nodejs
# vim
stow -d $DOTFILE_DIR -t $HOME vim-janus
# stow -d $DOTFILE_DIR -t $HOME vim

log_info "Relinked rc files."

log_info "Dead symbolic: "
find -L $HOME -maxdepth 3 -type l
