#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"

# base
stow -d $DIR -t $HOME shell git tmux crontab
# language
stow -d $DIR -t $HOME ruby lisp nodejs
# vim
stow -d $DIR -t $HOME vim-janus
# stow -d $DIR -t $HOME vim
