#!/bin/bash

[[ $(tmux has-session) ]] || \
  echo 'Waiting tmux server started. 15s' &&\
  $(tmux new-session -d -s tmp-session-for-start) &&\
  sleep 15

tm_sessions=$(ruby -e 'print `tmux list-sessions | cut -d ":" -f 1`.split.reject { |n| n == "tmp-session-for-start" }.map { |n| "\"#{n}\"" }.sort.join(", ")')
echo "[INFO] tmux sessions: ${tm_sessions}"

osascript << END
tell application "iTerm2"
  activate

  tell current window
    repeat with tm_session in {${tm_sessions}}
      create tab with default profile

      tell the last tab
        tell the last session
          set cmd to "tmux attach -t " & tm_session
          write text cmd
        end tell
      end tell
    end repeat

  end tell
end tell
END

tmux kill-session -t tmp-session-for-start
