#!/bin/sh

if [[ ! $DOT_SHELL_LIB_LEAD -eq 1 ]]; then
DOT_SHELL_LIB_LEAD=1

# DIR="$(cd "$(dirname "$0")" && pwd)"
# DIR="$(dirname "$(readlink -f "$0")")"
# echo $(pwd -P)

export CLICOLOR=1
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD

# history
# http://stackoverflow.com/questions/19454837/bash-histsize-vs-histfilesize
# http://zsh.sourceforge.net/Guide/zshguide02.html
export HISTFILESIZE=1000000
export HISTSIZE=${HISTFILESIZE}
export SAVEHIST=${HISTFILESIZE}

source $HOME/.lib/checks.sh

if [[ $HAS_NVIM -eq 1 ]]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
export LANG=en_US.UTF-8

# dotfiles custom bin file
# `brew install libtool` for mac first
if [[ $IS_MAC -eq 1 && -x `which gfind` ]]; then
  export GNU_FIND=gfind
elif [[ $IS_LINUX -eq 1 ]]; then
  export GNU_FIND=find
fi
if [[ -d $HOME/.bin/.third-party && -n $GNU_FIND ]]; then
  # http://unix.stackexchange.com/questions/17715/how-can-i-set-all-subdirectories-of-a-directory-into-path
  export PATH=$($GNU_FIND $HOME/.bin/.third-party/* -type d -printf "%p:")$PATH
fi
export PATH="$HOME/.bin:$PATH"

source $HOME/.lib/path.sh
source $HOME/.lib/alias.sh
source $HOME/.lib/functions.sh
if [[ -x `which fzf` ]]; then
  source $HOME/.lib/fzf.sh
fi

if [[ -e "$HOME/.lib/z.sh" ]]; then
  source $HOME/.lib/z.sh
fi
# https://github.com/asdf-vm/asdf
if [[ -e "$HOME/.asdf/asdf.sh" ]]; then
  source "$HOME/.asdf/asdf.sh"
  # source "$HOME/.asdf/completions/asdf.bash"
fi
# deliver
if [[ -e "$HOME/.deliver/bin/deliver" ]]; then export PATH="${PATH}:$HOME/.deliver/bin"; fi

# load custom profile
if [[ -e "$HOME/.lib/lead.local" ]]; then . "$HOME/.lib/lead.local"; fi

fi
