#!/bin/sh

if [[ ! $DOT_SHELL_LIB_LEAD -eq 1 ]]; then
DOT_SHELL_LIB_LEAD=1

# DIR="$(cd "$(dirname "$0")" && pwd)"
# DIR="$(dirname "$(readlink -f "$0")")"
# echo $(pwd -P)

export CLICOLOR=1
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD

source $HOME/.lib/checks.sh

if [[ $HAS_NVIM -eq 1 ]]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
export LANG=en_US.UTF-8

source $HOME/.lib/path.sh
source $HOME/.lib/alias.sh
source $HOME/.lib/functions.sh

# history
# http://stackoverflow.com/questions/19454837/bash-histsize-vs-histfilesize
# http://zsh.sourceforge.net/Guide/zshguide02.html
export HISTFILESIZE=100000
export HISTSIZE=${HISTFILESIZE}
export SAVEHIST=${HISTFILESIZE}

# dotfiles custom bin file
export PATH="$HOME/.bin:$PATH"
# load custom profile
if [[ -e "$HOME/.lib/lead.local" ]]; then . "$HOME/.lib/lead.local"; fi

fi
