#!/bin/sh

if [[ ! $DOT_SHELL_LIB_LEAD -eq 1 ]]; then
DOT_SHELL_LIB_LEAD=1

# DIR="$(cd "$(dirname "$0")" && pwd)"
# DIR="$(dirname "$(readlink -f "$0")")"
# echo $(pwd -P)

export CLICOLOR=1
# bsd
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
# linux
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

# history
# http://stackoverflow.com/questions/19454837/bash-histsize-vs-histfilesize
# http://zsh.sourceforge.net/Guide/zshguide02.html
export HISTFILESIZE=1000000
export HISTSIZE=${HISTFILESIZE}
export SAVEHIST=${HISTFILESIZE}

source $HOME/.lib/checks.sh

if [[ $IS_LINUX -eq 1 ]]; then
  # colored man pages
  export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
  export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
  export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
  export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
  export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
  export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
  export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan
fi

if [[ $HAS_NVIM -eq 1 ]]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# dotfiles custom bin file
# `brew install libtool` for mac first
if [[ $IS_MAC -eq 1 && -x `which gfind` ]] >/dev/null 2>&1; then
  export GNU_FIND=gfind
elif [[ $IS_LINUX -eq 1 ]]; then
  export GNU_FIND=find
fi
if [[ -d $HOME/.bin/.third-party && -n $GNU_FIND ]]; then
  # http://unix.stackexchange.com/questions/17715/how-can-i-set-all-subdirectories-of-a-directory-into-path
  export PATH=$($GNU_FIND $HOME/.bin/.third-party/* -type d -printf "%p:")$PATH
fi
export PATH="$HOME/.bin:$PATH"

source $HOME/.lib/path.sh
source $HOME/.lib/alias.sh
source $HOME/.lib/tmux.sh
source $HOME/.lib/functions.sh

# load custom profile
[[ -e "$HOME/.lib/lead.local" ]] && \
  source "$HOME/.lib/lead.local"

# remove duplicted path
# https://unix.stackexchange.com/questions/40749/remove-duplicate-path-entries-with-awk-command
PATH=$(printf %s "$PATH" | awk -v RS=: '{ if (!arr[$0]++) {printf("%s%s",!ln++?"":":",$0)}}')

fi
